"""add_order_delivery_address_fields

Revision ID: 05672193aa5b
Revises: 5019bba19922
Create Date: 2026-06-19 18:39:33.991455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05672193aa5b'
down_revision = '5019bba19922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_name')
        batch_op.drop_column('delivery_phone')
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
