""" add negotiation tables and product negotiation fields

Revision ID: 20eee4b60e25
Revises: 361cb0130ee5
Create Date: 2026-05-22 22:12:39.067692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eee4b60e25'
down_revision = '361cb0130ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
