""" Add is_deleted to products

Revision ID: 39462a06a1b3
Revises: 35fa50cb6baa
Create Date: 2026-06-07 07:16:22.275762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39462a06a1b3'
down_revision = '35fa50cb6baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
