"""add_partner_bank_and_pricing_fields

Revision ID: 5019bba19922
Revises: e3bea16ab4f2
Create Date: 2026-06-19 18:36:11.598157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5019bba19922'
down_revision = 'e3bea16ab4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pricing_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_applications', schema=None) as batch_op:
        batch_op.drop_column('pricing_settings')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_code')

    # ### end Alembic commands ###
