"""add product_type file_url booking_link sku weight seo fields

Revision ID: 54d6b6b06341
Revises: 39462a06a1b3
Create Date: 2026-06-08 00:45:34.576009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d6b6b06341'
down_revision = '39462a06a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('booking_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('weight')
        batch_op.drop_column('sku')
        batch_op.drop_column('booking_link')
        batch_op.drop_column('file_url')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
