"""add product_type file_url booking_link sku weight seo fields

Revision ID: 54d6b6b06341
Revises: 39462a06a1b3
Create Date: 2026-06-08 00:45:34.576009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d6b6b06341'
down_revision = '39462a06a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # Use IF NOT EXISTS via raw SQL on PostgreSQL to be fully idempotent.
    # These columns may already exist on production if they were applied
    # out-of-band before this migration file was committed to the codebase.
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == 'postgresql':
        statements = [
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type VARCHAR(20)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS file_url VARCHAR(500)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS booking_link VARCHAR(500)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS sku VARCHAR(100)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS weight NUMERIC(8, 2)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title VARCHAR(255)",
            "ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description TEXT",
        ]
        for stmt in statements:
            bind.execute(sa.text(stmt))

        # Set default value for existing rows where product_type is NULL
        bind.execute(sa.text(
            "UPDATE products SET product_type = 'physical' WHERE product_type IS NULL"
        ))
    else:
        # SQLite / other — use batch_alter_table (safe on fresh DBs)
        from sqlalchemy.engine.reflection import Inspector
        inspector = Inspector.from_engine(bind)
        columns = [c['name'] for c in inspector.get_columns('products')]

        with op.batch_alter_table('products', schema=None) as batch_op:
            if 'product_type' not in columns:
                batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=True))
            if 'file_url' not in columns:
                batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
            if 'booking_link' not in columns:
                batch_op.add_column(sa.Column('booking_link', sa.String(length=500), nullable=True))
            if 'sku' not in columns:
                batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
            if 'weight' not in columns:
                batch_op.add_column(sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True))
            if 'seo_title' not in columns:
                batch_op.add_column(sa.Column('seo_title', sa.String(length=255), nullable=True))
            if 'seo_description' not in columns:
                batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('weight')
        batch_op.drop_column('sku')
        batch_op.drop_column('booking_link')
        batch_op.drop_column('file_url')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
