"""add payscrow escrow_code

Revision ID: 93b4a8e2b83c
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b4a8e2b83c'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payscrow_transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('escrow_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_transactions', schema=None) as batch_op:
        batch_op.drop_column('escrow_code')
        batch_op.drop_column('payscrow_transaction_id')

    # ### end Alembic commands ###
