"""Add storefront builder fields

Revision ID: aa3e829401e7
Revises: e7698ebf4ee9
Create Date: 2026-05-08 18:38:05.893626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3e829401e7'
down_revision = 'e7698ebf4ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cac_reg', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('template_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('social_links', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('working_hours', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('points_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True))
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_column('points_balance')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.drop_column('working_hours')
        batch_op.drop_column('social_links')
        batch_op.drop_column('template_options')
        batch_op.drop_column('cac_reg')
        batch_op.drop_column('website')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
