"""Add template_options to BrandingSettings

Revision ID: b7201c8e9fa1
Revises: ea362e02b64f
Create Date: 2026-05-15 11:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7201c8e9fa1'
down_revision = 'ea362e02b64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_settings', schema=None) as batch_op:
        batch_op.drop_column('template_options')
    # ### end Alembic commands ###
