"""Add category to article

Revision ID: c6ea6d7135fa
Revises: 3a4b5c6d7e8f
Create Date: 2026-06-02 15:50:23.533786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6ea6d7135fa'
down_revision = '3a4b5c6d7e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('invoices_order_id_key'), type_='unique')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('receipts_order_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_receipts_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_vendor_id'))
        batch_op.create_unique_constraint(batch_op.f('receipts_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('line_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('invoices_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('line_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
