"""Add NIN and identity document verification fields

Revision ID: e3bea16ab4f2
Revises: f6b7c8d9e0f1
Create Date: 2026-06-13 12:29:27.868521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bea16ab4f2'
down_revision = 'f6b7c8d9e0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False, server_default='INDIVIDUAL'))
        batch_op.add_column(sa.Column('nin_document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cac_document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=False, server_default='NOT_SUBMITTED'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nin', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nin')

    with op.batch_alter_table('storefronts', schema=None) as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('cac_document_url')
        batch_op.drop_column('nin_document_url')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
